title:            Ravi Lazar
tagline:          How many r's in strawberry?
description:      Blog of Ravi Kumar.
#Comment out url when working locally to resolve base urls correctly
url:
#Variables for the feed
name: Ravi Lazar
furl: https://blog.ravilazar.com


#A dirty bug-fix https://github.com/mojombo/jekyll/issues/1401
excerpt_separator: ""


# Owner/author information
owner:
  name:           Ravi Kumar
  avatar:         avatar.png
  bio:            "A newbie Web-developer and Programmer"
  twitter:        ravikml
  github:         upman
  disqus:         upman
  # Plug in your disqus shortname!


# Links to include in top navigation
# For external links add external: true
links:
  - title: Github
    url: https://github.com/upman
    external: true
  - title: Linkedin
    url: https://www.linkedin.com/in/ravikml/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Calcutta
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Sass configuration
sass:
  sass_dir: assets/sass
  style: compressed

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
