title:            Ravi Kumar
tagline:          Adeventures of a newbie web developer
description:      Blog of Ravi Kumar.
#Comment out url when working locally to resolve base urls correctly
url:
#Variables for the feed
name: Ravi Kumar
description: Blog of Ravi Kumar
furl: http://upman.github.com


#A dirty bug-fix https://github.com/mojombo/jekyll/issues/1401
excerpt_separator: ""


# Owner/author information
owner: 
  name:           Ravi Kumar
  avatar:         avatar.png
  bio:            "A newbie Web-developer and Programmer"
  email:          upman16@gmail.com
  twitter:        upman16        
  github:         upman       
  instagram:           
  dribbble:
  facebook:       ravi.kumar1607
  disqus:         upman
  # Plug in your disqus shortname!
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/index.html
  - title: Github
    url: https://github.com/upman
    external: true
  - title: Ravi Who?
    url: https://www.facebook.com/ravi.kumar1607/about
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Calcutta#America/New_York
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
